name: Deploy React Application

on:
  push:
    branches:
      - main

  # workflow_dispatch: # Manually trigger workflow
  #   inputs:
  #     custom-trigger:
  #       description: 'Trigger the workflow manually'
  #       required: false
  #       default: 'manual'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Build Docker Image
        run: docker build -t shanukafer98/ranhuya-frontend .
      - name: Publish image to docker hub
        run: docker push shanukafer98/ranhuya-frontend:latest   

  deploy: 
    needs: build
    runs-on: self-hosted   
    steps:
      - name: Pull image from docker hub
        run: docker pull shanukafer98/ranhuya-frontend:latest
      - name: Delete Old Container
        run: docker rm -f react-app-container
      - name: Run docker container
        run: docker run -d -p 5173:5173 --name react-app-container shanukafer98/ranhuya-frontend